name: 'Azure Deployment Environments'
description: 'Create Azure Deployment Environments on demand for branches and pull releases.'
author: 'ColbyLWilliams'
inputs:
  action:
    description: 'Action to take on the environment. Can be setup, get, create, update, ensure, delete, or auto.'
    required: true
    default: 'setup'
  tenant:
    description: 'The Azure tenant ID (GUID).'
    required: false
  subscription:
    description: 'The Azure subscription (GUID).'
    required: false
  devcenter:
    description: 'The DevCenter name.'
    required: false
  project:
    description: 'The Project name.'
    required: false
  catalog:
    description: 'The name of the Catalog.'
    required: false
  catalog-item:
    description: 'The name of the Catalog Item.'
    required: false
  prefix:
    description: 'The prefix for the resolved environment name. If none is provided, environment names will start with ci.'
    required: false
  suffix:
    description: 'The suffix for the resolved environment name. If none is provided, environment names will end with the repository numeric id.'
    required: false
  main-branch:
    description: 'The name of the main branch. Defaults to main.'
    required: false
  dev-branch:
    description: 'The name of the dev branch. If a value is provided, the action assums feature branches are created from the dev branch and the dev branch is merged into main for production deployments.'
    required: false
  prod-environment-name:
    description: 'Override the name of the production environment. If not specified, it will be generated.'
    required: false
  prod-environment-type:
    description: 'The name of the production environment type where the main branch will be deployed. Defaults to Prod.'
    required: false
  staging-environment-type:
    description: 'The name of the staging environment type. If dev-branch is specified, pull requests from the dev branche to the main branch will create environments in this environment type. Defaults to Staging.'
    required: false
  test-environment-type:
    description: 'The name of the testing environment type. If dev-branch is specified, pull requests from feature branches to the dev branch will create environments in this environment type. If feature branches are created from main, pull requests from feature branches to the main will use this type. Defaults to Test.'
    required: false
  dev-environment-type:
    description: 'The name of the development environment type. Feature branches will create environments in this environment type. Defaults to Dev.'
    required: false
  parameters:
    description: 'A JSON string containing parameters for the environment.'
    required: false
  config:
    description: 'Path to a YAML configuration file.'
    required: false
    default: 'ade.yml'
  devcenter-extension:
    description: 'The url to a specific version of the Azure CLI DevCenter Extension.'
    required: false
outputs:
  tenant:
    description: 'The environment tenant (GUID).'
  subscription:
    description: 'The environment subscription (GUID).'
  resource-group:
    description: 'The name of the environment resource group.'
  resource-group-id:
    description: 'The resource id of the environment resource group.'
  exists:
    description: 'True if the environment exists otherwise False.'
  created:
    description: 'True if the environment was created by the action otherwise False.'
  portal-url:
    description: 'Url to the environment resource group in the azure portal.'
  name:
    description: 'The environment name.'
  type:
    description: 'The environment type.'
runs:
  using: 'node16'
  main: 'dist/index.js'
