name: 'Azure Deployment Environments'
description: 'Create Azure Deployment Environments on demand for branches and pull releases.'
author: 'ColbyLWilliams'
inputs:
  action:
    required: true
    description: 'Action to take on the environment. Can be setup, get, create, update, ensure, or delete.'
    default: 'setup'
  tenant:
    required: false
    description: 'The Azure tenant ID (GUID).'
  subscription:
    required: false
    description: 'The Azure subscription (GUID).'
  devcenter:
    required: false
    description: 'The DevCenter name.'
  project:
    required: false
    description: 'The Project name.'
  catalog:
    required: false
    description: 'The name of the Catalog.'
  catalog-item:
    required: false
    description: 'The name of the Catalog Item.'
  prefix:
    required: false
    description: 'The prefix for the resolved environment name. If none is provided, environment names will start with ci.'
    default: 'ci'
  suffix:
    required: false
    description: 'The suffix for the resolved environment name. If none is provided, environment names will start with the repositorys id.'
    default: ${{ github.repository_id }}
  main-branch:
    required: false
    description: 'The name of the main branch. Defaults to main.'
    default: 'main'
  dev-branch:
    required: false
    description: 'The name of the dev branch. If a value is provided, the action assums feature branches are created from the dev branch and the dev branch is merged into main for production deployments.'
  prod-environment-name:
    required: false
    description: 'Override the name of the production environment. If not specified, it will be generated.'
  prod-environment-type:
    required: false
    description: 'The name of the production environment type where the main branch will be deployed.'
    default: 'Prod'
  staging-environment-type:
    required: false
    description: 'The name of the staging environment type. If dev-branch is specified, pull requests from the dev branche to the main branch will create environments in this environment type.'
    default: 'Staging'
  test-environment-type:
    required: false
    description: 'The name of the testing environment type. If dev-branch is specified, pull requests from feature branches to the dev branch will create environments in this environment type. If feature branches are created from main, pull requests from feature branches to the main will use this type.'
    default: 'Test'
  dev-environment-type:
    required: false
    description: 'The name of the development environment type. Feature branches will create environments in this environment type.'
    default: 'Dev'
  parameters:
    required: false
    description: ''
  config:
    required: false
    description: 'Path to a YAML configuration file.'
    default: 'ade.yml'
outputs:
  tenant:
    description: 'The environment tenant (GUID).'
  subscription:
    description: 'The environment subscription (GUID).'
  resource-group:
    description: 'The name of the environment resource group.'
  resource-group-id:
    description: 'The resource id of the environment resource group.'
  exists:
    description: 'True if the environment exists otherwise False.'
  created:
    description: 'True if the environment was created by the action otherwise False.'
  portal-url:
    description: 'Url to the environment resource group in the azure portal.'
  name:
    description: 'The environment name.'
  type:
    description: 'The environment type.'
runs:
  using: 'node16'
  main: 'dist/index.js'
